apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: go-builder
  namespace: default
spec:
  serviceAccountName: local-service-account
  tag: gcr.io/cnb-playground/kpack-go-builder
  stack:
    name: go-local-stack
    kind: ClusterStack
  store:
    name: go-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/go
